import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import employeesRouter from "./employees";
import attendanceRouter from "./attendance";
import attendanceExtensionRouter from "./attendance-extension";
import leavesRouter from "./leaves";
import payslipsRouter from "./payslips";
import dashboardRouter from "./dashboard";
import remoteWorkRouter from "./remote-work";
import generalRequestsRouter from "./general-requests";
import uploadsRouter from "./uploads";
import settingsRouter from "./settings";
import salaryComponentsRouter from "./salary-components";
import newsRouter from "./news";
import loansRouter from "./loans";
import inventoryRouter from "./inventory";
import monthlyViewRouter from "./monthly-view";
import medicalRouter from "./medical";
import notificationsRouter from "./notifications";
import standupsRouter from "./standups";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(employeesRouter);
router.use(attendanceRouter);
router.use(attendanceExtensionRouter);
router.use(leavesRouter);
router.use(payslipsRouter);
router.use(dashboardRouter);
router.use(remoteWorkRouter);
router.use(generalRequestsRouter);
router.use(uploadsRouter);
router.use(settingsRouter);
router.use(salaryComponentsRouter);
router.use(newsRouter);
router.use(loansRouter);
router.use(inventoryRouter);
router.use(monthlyViewRouter);
router.use(medicalRouter);
router.use(notificationsRouter);
router.use(standupsRouter);

export default router;
